steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'mlops-cat-classifier/Dockerfile.api'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/group8repo/cat-classifier-api:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/group8repo/cat-classifier-api:latest'
      - './mlops-cat-classifier'

  # Push image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/group8repo/cat-classifier-api:$SHORT_SHA'

  # Push image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/group8repo/cat-classifier-api:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cat-classifier-api'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/group8repo/cat-classifier-api:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8000'
      - '--cpu'
      - '2'
      - '--memory'
      - '4G'
      - '--timeout'
      - '300'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
